feat: :alien: updated yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,16 +1,20 @@
 name: Push-to-EC2
+ 
 # Trigger deployment only on push to main branch
 on:
   push:
     branches:
       - main
+ 
 jobs:
   deploy:
     name: Deploy to EC2 on main branch push
     runs-on: ubuntu-latest
+ 
     steps:
       - name: Checkout the files
         uses: actions/checkout@v2
+ 
       # Deploy to Server 1
       - name: Deploy to Server 1
         uses: easingthemes/ssh-deploy@main
@@ -18,8 +22,19 @@ jobs:
           SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
           REMOTE_HOST: ${{ secrets.HOST_DNS1 }}
           REMOTE_USER: ${{ secrets.USERNAME }}
-          TARGET: ${{ secrets.TARGET_DIR }}
-      - name: Executing remote ssh commands on Server 1
+          TARGET: /home/ubuntu
+ 
+      - name: Verify files after deployment on Server 1
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.HOST_DNS1 }}
+          username: ${{ secrets.USERNAME }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            echo "Listing contents of /home/ubuntu:"
+            ls -l /home/ubuntu
+ 
+      - name: Install Apache and move files to Apache directory on Server 1
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST_DNS1 }}
@@ -30,17 +45,54 @@ jobs:
             sudo apt-get install -y apache2
             sudo systemctl start apache2
             sudo systemctl enable apache2
-            cd home
-            sudo mv * /var/www/html
-      # Deploy to Server 2
+            sudo mv /home/ubuntu/* /var/www/html
+ 
+      - name: Verify files in Apache directory on Server 1
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.HOST_DNS1 }}
+          username: ${{ secrets.USERNAME }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            echo "Listing contents of /var/www/html:"
+            ls -l /var/www/html
+ 
+      - name: Modify index.html for Server 1
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.HOST_DNS1 }}
+          username: ${{ secrets.USERNAME }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            PRIVATE_IP=$(hostname -I | awk '{print $1}')
+            FILE_PATH="/var/www/html/index.html"
+            if [ -f "$FILE_PATH" ]; then
+              sudo sed -i "s/\$(hostname -f)/$PRIVATE_IP/" "$FILE_PATH"
+            else
+              echo "Error: File $FILE_PATH not found."
+              exit 1
+            fi
+ 
+      # Deploy to Server 2 (similar steps as Server 1)
       - name: Deploy to Server 2
         uses: easingthemes/ssh-deploy@main
         env:
           SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
           REMOTE_HOST: ${{ secrets.HOST_DNS2 }}
           REMOTE_USER: ${{ secrets.USERNAME }}
-          TARGET: ${{ secrets.TARGET_DIR }}
-      - name: Executing remote ssh commands on Server 2
+          TARGET: /home/ubuntu
+ 
+      - name: Verify files after deployment on Server 2
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.HOST_DNS2 }}
+          username: ${{ secrets.USERNAME }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            echo "Listing contents of /home/ubuntu:"
+            ls -l /home/ubuntu
+ 
+      - name: Install Apache and move files to Apache directory on Server 2
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST_DNS2 }}
@@ -51,8 +103,34 @@ jobs:
             sudo apt-get install -y apache2
             sudo systemctl start apache2
             sudo systemctl enable apache2
-            cd home
-            sudo mv * /var/www/html
+            sudo mv /home/ubuntu/* /var/www/html
+ 
+      - name: Verify files in Apache directory on Server 2
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.HOST_DNS2 }}
+          username: ${{ secrets.USERNAME }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            echo "Listing contents of /var/www/html:"
+            ls -l /var/www/html
+ 
+      - name: Modify index.html for Server 2
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.HOST_DNS2 }}
+          username: ${{ secrets.USERNAME }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            PRIVATE_IP=$(hostname -I | awk '{print $1}')
+            FILE_PATH="/var/www/html/index.html"
+            if [ -f "$FILE_PATH" ]; then
+              sudo sed -i "s/\$(hostname -f)/$PRIVATE_IP/" "$FILE_PATH"
+            else
+              echo "Error: File $FILE_PATH not found."
+              exit 1
+            fi
+
       # Deploy to Server 3
       - name: Deploy to Server 3
         uses: easingthemes/ssh-deploy@main
@@ -60,8 +138,19 @@ jobs:
           SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
           REMOTE_HOST: ${{ secrets.HOST_DNS3 }}
           REMOTE_USER: ${{ secrets.USERNAME }}
-          TARGET: ${{ secrets.TARGET_DIR }}
-      - name: Executing remote ssh commands on Server 3
+          TARGET: /home/ubuntu
+ 
+      - name: Verify files after deployment on Server 3
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.HOST_DNS3 }}
+          username: ${{ secrets.USERNAME }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            echo "Listing contents of /home/ubuntu:"
+            ls -l /home/ubuntu
+ 
+      - name: Install Apache and move files to Apache directory on Server 3
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST_DNS3 }}
@@ -72,8 +161,33 @@ jobs:
             sudo apt-get install -y apache2
             sudo systemctl start apache2
             sudo systemctl enable apache2
-            cd home
-            sudo mv * /var/www/html
+            sudo mv /home/ubuntu/* /var/www/html
+ 
+      - name: Verify files in Apache directory on Server 3
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.HOST_DNS3 }}
+          username: ${{ secrets.USERNAME }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            echo "Listing contents of /var/www/html:"
+            ls -l /var/www/html
+ 
+      - name: Modify index.html for Server 3
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.HOST_DNS3 }}
+          username: ${{ secrets.USERNAME }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            PRIVATE_IP=$(hostname -I | awk '{print $1}')
+            FILE_PATH="/var/www/html/index.html"
+            if [ -f "$FILE_PATH" ]; then
+              sudo sed -i "s/\$(hostname -f)/$PRIVATE_IP/" "$FILE_PATH"
+            else
+              echo "Error: File $FILE_PATH not found."
+              exit 1
+            fi
       # Deploy to Server 4
       - name: Deploy to Server 4
         uses: easingthemes/ssh-deploy@main
@@ -81,8 +195,19 @@ jobs:
           SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
           REMOTE_HOST: ${{ secrets.HOST_DNS4 }}
           REMOTE_USER: ${{ secrets.USERNAME }}
-          TARGET: ${{ secrets.TARGET_DIR }}
-      - name: Executing remote ssh commands on Server 4
+          TARGET: /home/ubuntu
+ 
+      - name: Verify files after deployment on Server 4
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.HOST_DNS4 }}
+          username: ${{ secrets.USERNAME }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            echo "Listing contents of /home/ubuntu:"
+            ls -l /home/ubuntu
+ 
+      - name: Install Apache and move files to Apache directory on Server 4
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST_DNS4 }}
@@ -93,5 +218,32 @@ jobs:
             sudo apt-get install -y apache2
             sudo systemctl start apache2
             sudo systemctl enable apache2
-            cd home
-            sudo mv * /var/www/html
+            sudo mv /home/ubuntu/* /var/www/html
+ 
+      - name: Verify files in Apache directory on Server 4
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.HOST_DNS4 }}
+          username: ${{ secrets.USERNAME }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            echo "Listing contents of /var/www/html:"
+            ls -l /var/www/html
+ 
+      - name: Modify index.html for Server 4
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.HOST_DNS4 }}
+          username: ${{ secrets.USERNAME }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            PRIVATE_IP=$(hostname -I | awk '{print $1}')
+            FILE_PATH="/var/www/html/index.html"
+            if [ -f "$FILE_PATH" ]; then
+              sudo sed -i "s/\$(hostname -f)/$PRIVATE_IP/" "$FILE_PATH"
+            else
+              echo "Error: File $FILE_PATH not found."
+              exit 1
+            fi
+ 
+    
